# Generated by Django 2.2.13 on 2020-06-17 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_city_settings"),
        ("users", "0002_auto_20200617_2152"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="settings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_settings",
                to="home.Settings",
            ),
        ),
    ]
