# Generated by Django 2.2.13 on 2020-06-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
